source $HOME/.config/bash/lib/aliases.sh
source $HOME/.config/bash/lib/cdparentdirs.sh
source $HOME/.config/bash/lib/git.sh
source $HOME/.config/bash/lib/ls.sh
source $HOME/.config/bash/lib/mark_recall.sh
source $HOME/.config/bash/lib/mkcd.sh
source $HOME/.config/bash/lib/notes.sh
source $HOME/.config/bash/lib/scratch.sh
source $HOME/.config/bash/lib/shortcuts.sh
source $HOME/.config/bash/lib/tmux.sh

export EDITOR='nvim'
export GREP_OPTIONS='--extended-regexp'
export HISTFILE=$HOME/.config/bash/history
export HISTIGNORE='a:c:ls:lao:lol:clear:exit'
export HISTSIZE=10000
export LESS='--quit-on-intr --RAW-CONTROL-CHARS --ignore-case'
export MYVIMRC=$HOME/.config/vim/vimrc
export PAGER='less'
export PROMPT_COMMAND='history -a; history -r'
export SAM_CLI_TELEMETRY=0
export VIMINIT='source $MYVIMRC'
#export VIMRUNTIME=$HOME/src/neovim/runtime
export XDG_CONFIG_HOME="$HOME/.config"

stty -ixon
stty ixoff
stty ixany
